spring:
  application:
    name: smile-server
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.xml
